# Generated by Django 4.2.2 on 2024-07-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="lesson/images/",
                verbose_name="Превью урока",
            ),
        ),
    ]
